### ISSUE TITLE
Add gh-pages branch for demo

### ISSUE THREAD

**Issue by gillchristian** [tamagokun/example-react-dnd-nested#3]
The example is really nice, it would be cool to see the demo online.

**Comment by tamagokun** [comment]
Oh, yeah, definitely. I hate it when there isn't a demo to see what's happening. Will have to add this!

**Comment by gillchristian** [comment]
I actually did it on my fork, but can't PR to an nonexistent branch haha.

**Comment by tamagokun** [comment]
Oh nice, just a moment!

**Comment by tamagokun** [comment]
Ok, try now!

**Comment by gillchristian** [comment]
Sorry for the delay, finally was able to take 5 minutes to do this :smile:

As I already opened #4 this issue can be closed.

**Comment by tamagokun** [comment]
sweeeeeeet. looks great. Thanks so much!
